=== NAzT/SOA_Asg2_Nat/build/FlightReservation.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/FlightReservation"
    xmlns:tns="http://xml.netbeans.org/schema/FlightReservation"
    elementFormDefault="qualified">
    <xsd:simpleType name="TimeList">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Any"/>
            <xsd:enumeration value="12 AM"/>
            <xsd:enumeration value="1 AM"/>
            <xsd:enumeration value="2 AM"/>
            <xsd:enumeration value="3 AM"/>
            <xsd:enumeration value="4 AM"/>
            <xsd:enumeration value="5 AM"/>
            <xsd:enumeration value="6 AM"/>
            <xsd:enumeration value="7 AM"/>
            <xsd:enumeration value="8 AM"/>
            <xsd:enumeration value="9 AM"/>
            <xsd:enumeration value="10 AM"/>
            <xsd:enumeration value="11 AM"/>
            <xsd:enumeration value="12 PM"/>
            <xsd:enumeration value="1 PM"/>
            <xsd:enumeration value="2 PM"/>
            <xsd:enumeration value="3 PM"/>
            <xsd:enumeration value="4 PM"/>
            <xsd:enumeration value="5 PM"/>
            <xsd:enumeration value="6 PM"/>
            <xsd:enumeration value="7 PM"/>
            <xsd:enumeration value="8 PM"/>
            <xsd:enumeration value="9 PM"/>
            <xsd:enumeration value="10 PM"/>
            <xsd:enumeration value="11 PM"/>
            <xsd:enumeration value="Morn."/>
            <xsd:enumeration value="Noon"/>
            <xsd:enumeration value="Eve."/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="AirlineClasses">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Economy">
                <xsd:annotation>
                    <xsd:documentation>Economy Coach</xsd:documentation>
                </xsd:annotation>
            </xsd:enumeration>
            <xsd:enumeration value="Premium">
                <xsd:annotation>
                    <xsd:documentation>Premium Economy</xsd:documentation>
                </xsd:annotation>
            </xsd:enumeration>
            <xsd:enumeration value="Business">
                <xsd:annotation>
                    <xsd:documentation>Business</xsd:documentation>
                </xsd:annotation>
            </xsd:enumeration>
            <xsd:enumeration value="FirstClass">
                <xsd:annotation>
                    <xsd:documentation>First Class</xsd:documentation>
                </xsd:annotation>
            </xsd:enumeration>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="AirlinesList">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="American Airlines"/>
            <xsd:enumeration value="China Airlines"/>
            <xsd:enumeration value="EVA Airways"/>
            <xsd:enumeration value="Thai Air International"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="TicketType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Roundtrip"/>
            <xsd:enumeration value="One Way"/>
            <xsd:enumeration value="Multiple definitions"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="ServiceType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Flight"/>
            <xsd:enumeration value="Hotel"/>
            <xsd:enumeration value="Car"/>
            <xsd:enumeration value="Cruise"/>
            <xsd:enumeration value="Activities"/>
            <xsd:enumeration value="Flight + Hotel"/>
            <xsd:enumeration value="Flight + Car"/>
            <xsd:enumeration value="Flight + Hotel + Car"/>
            <xsd:enumeration value="Hotel + Car"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="passengerType">
        <xsd:sequence>
            <xsd:element name="Adults" type="tns:passengerConstraint"/>
            <xsd:element name="Seniors" type="tns:passengerConstraint"/>
            <xsd:element name="Childrens" type="tns:passengerConstraint"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="passengerConstraint">
        <xsd:restriction base="xsd:integer">
            <xsd:maxExclusive value="6"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="FlightReservationType">
        <xsd:sequence>
            <xsd:element name="Service" type="tns:ServiceType"></xsd:element>
            <xsd:element name="Ticket" type="tns:TicketType"></xsd:element>
            <xsd:element name="LeavingFrom" type="xsd:string"></xsd:element>
            <xsd:element name="GoingTo" type="xsd:string"></xsd:element>
            <xsd:element name="DepartingDate" type="xsd:date"/>
            <xsd:element name="DapartingTime" type="tns:TimeList"/>
            <xsd:element name="ReturningDate" type="xsd:date"/>
            <xsd:element name="ReturningTime" type="tns:TimeList"/>
            <xsd:element name="Passengers" type="tns:passengerType"/>
            <xsd:element name="NonStopOnly" type="xsd:boolean"/>
            <xsd:element name="AvoidMostChangePenalty" type="xsd:boolean"/>
            <xsd:element name="Airline" type="tns:AirlinesList"/>
            <xsd:element name="AirlineClass" type="tns:AirlineClasses"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="FlightReservation" type="tns:FlightReservationType"></xsd:element>
</xsd:schema>

=== NAzT/SOA_Asg2_Nat/src/FlightReservation.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : FlightReservation1.xml
    Created on : September 21, 2009, 5:55 AM
    Author     : NAzT
    Description:
        Purpose of the document follows.
-->

<ns0:FlightReservation  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/FlightReservation'
   xsi:schemaLocation='http://xml.netbeans.org/schema/FlightReservation FlightReservation.xsd'>
  <ns0:Service>Flight</ns0:Service>
    <ns0:Ticket>One Way</ns0:Ticket>
    <ns0:LeavingFrom>USA</ns0:LeavingFrom>
    <ns0:GoingTo>Bangkok</ns0:GoingTo>
    <ns0:DepartingDate>2009-08-11</ns0:DepartingDate>
    <ns0:DapartingTime>10 AM</ns0:DapartingTime>
    <ns0:ReturningDate>2009-08-13</ns0:ReturningDate>
    <ns0:ReturningTime>1 AM</ns0:ReturningTime>
    <ns0:Passengers>
        <ns0:Adults>3</ns0:Adults>
        <ns0:Seniors>5</ns0:Seniors>
        <ns0:Childrens>2</ns0:Childrens>
    </ns0:Passengers>
    <ns0:NonStopOnly>false</ns0:NonStopOnly>
    <ns0:AvoidMostChangePenalty>true</ns0:AvoidMostChangePenalty>
    <ns0:Airline>American Airlines</ns0:Airline>
    <ns0:AirlineClass>FirstClass</ns0:AirlineClass>


</ns0:FlightReservation>
